### ISSUE TITLE
Simulation Testing Issues

### ISSUE THREAD

**Issue by rschenck** [rschenck/game_of_life#16]
I've ran a few simulations for iPhone/iPhone Plus (5 and 6) as well as iPad Air, iPad Pro etc.

Here's a few problems I'm seeing:
1) Images aren't loading (primarily the buttons). Everything image, font, and music wise appears to be loading okay. (I like the Game Over Screen with just pure black. It looks good with just the Play Again blinking)
![done](https://cloud.githubusercontent.com/assets/7303435/19450236/9f0592d0-9476-11e6-918e-62228b2a37a7.jpg)

2) Formatting of the popups for Restart and Main Menu are off. See attached. Main Menu button doesn't work when in game mode (Not sure if this is due to formatting or the button purely doesn't work).
![main_menu](https://cloud.githubusercontent.com/assets/7303435/19449612/3fb68f2a-9474-11e6-8b6e-557f33cb8761.jpg)
![restart](https://cloud.githubusercontent.com/assets/7303435/19449645/6c9dac3a-9474-11e6-9545-08a84db52a62.jpg)

3) The options and Select Pattern appear to be a bit to small to use with a finger.
![sel copy](https://cloud.githubusercontent.com/assets/7303435/19450048/e9a92c58-9475-11e6-9257-143eab7d1208.jpg)

Overall I think it's just about finished if we can figure out these issues. Need to get it submitted to apple for approval (fingers crossed)

**Comment by sleekramer** [comment]
Not a simulation problem, but when you close the opening graphic, the main menu is presented but all buttons are active as well.

**Comment by sleekramer** [comment]
the formatting seems to reflect the code on the popups.  discrepancy is due to the use of dp() and px i think.  computers

**Comment by rschenck** [comment]
Yea, the main menu with the buttons all active is an issue. Not sure why it's doing that.

I'm working on fixing the formatting issues now. I've fixed quite a few and added a way to compare across similar devices only for the scoring.

**Comment by rschenck** [comment]
The Select patterns thing I'm just going to make bigger. It takes up very little space on the screen during the simulations.

**Comment by rschenck** [comment]
The reason that the main_menu does that is because it's being attached to the board while the others are not being attached to the board.

**Comment by sleekramer** [comment]
where is it being attached to the board?

**Comment by rschenck** [comment]
It was. I have since changed it in the game-mode-clean branch

But I just added,
event = Clock.schedule_once(main_menu.open)
event()

This opens it behind the main image.
