### ISSUE TITLE
Create Scoring Mechanism

### ISSUE THREAD

**Issue by rschenck** [rschenck/game_of_life#3]
Adding a mechanism for adding up a "Score"

Idea:
-Only allow scoring on a plus sign start
-Can place individual squares, not draw
-Update score every n-th frame
-Save the users High score
-Top right corner have a current score and a High Score
-Create a popup for whenever a High Score is achieved
-Disable scoring for all other functions (i.e. When the default rules aren't met, when starting from a different preset)

**Comment by sleekramer** [comment]
scoring method ideas:
- keep track of all live cells and have some way of detecting, when the game has reached its stable conclusion.
- keep a activate(+) / death(-) ratio for the entire run of the game.  i.e. 600 cells activated to 400 deaths --> score of 200.

**Comment by rschenck** [comment]
How would we define a stable conclusion? I was planning on Keeping track of all live cells. But I'm not sure when it should 'end'

Maybe a clock? There's a timer for the user to reach as high a score as possible in 30secs and then a score is calculated and given?

**Comment by rschenck** [comment]
Scoring could be:
Score = All living cells +( ratio of alive / death)

**Comment by sleekramer** [comment]
a clock would work, but also I was thinking that at some point the alive/death ratio would stabilize or fluctuate a small amount at the end.  So, we could keep track of the last 10-15 alive/death ratio scores and if they cycle or have shown a consistent change of <= x (x = 10 or something), then we could say the game is over.  This seems wouldn't be too hard to implement, but it does assume a few things that we would have to confirm.

**Comment by rschenck** [comment]
Cool. I like that. But I think we should implement a clock as well to keep track of that. This way the user isn't able to just keep placing cells.

**Comment by sleekramer** [comment]
What if we used a number of iterations instead of a clock?
And only allow the user one click per (alive / death) point at any given step.

**Comment by rschenck** [comment]
That would be pretty dope! We should discuss that more

Please excuse any mistakes as this e-mail was sent from my iPhone.

**Comment by sleekramer** [comment]
Some thoughts / specs:
1. Track score with counters:
   - all_activated = # of cells activated
   - a_d_ratio = activated - died
2.  The a_d_ratio can be linked to the click handlers to allow the user to add cells.  Each cell will result in a deduction of 1 from the a_d_ratio score.  When the score reaches 0, the user can no longer place cells
3. Keep a decrementing count of generations.  I think somewhere in the range of 500-1000 would be good.  We could add the ability to pick different lengths of games
   - Need to end the game once the generations count hits 0
4. Highscore
   - Need a way to save this data

**Comment by sleekramer** [comment]
Also, if there are no live cells left the game should automatically end.
And if there are no changes in the changes_dict after get_cell_changes(), the game should be paused.  Then if there are no clicks available, the game should end.
