### ISSUE TITLE
Track all cells that have ever been alive and color them grey

### ISSUE THREAD

**Issue by sleekramer** [rschenck/game_of_life#6]
instead of just tracking 1 or 0 for alive or dead, we could assign a 2 for a cell that has been alive.  Then we could use an enum class to assign one of three values: 
- 0 = dead and has never been alive
- 1 = alive
- 2 = was alive once but now is dead.

**Comment by rschenck** [comment]
Do we want to color the dead ones? Would it get to crowded/busy?

**Comment by sleekramer** [comment]
I don't think so.  the right shade of grey should be muted enough to not interfere with the game graphics

**Comment by sleekramer** [comment]
dead and never been alive is "colored" black / just not colored, which we don't need to change

**Comment by rschenck** [comment]
Okay sounds good. We should get some feedback afterwards to see how people like that
